version: '3.8'

services:
  sncroniza:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3333:3333"           # Map port 3333 of the container to port 3333 on the host
    environment:
      - NODE_ENV=production   

